<?php include 'auth.php'; include 'header.php';
$edit = null;
if(isset($_GET['delete'])){ $id=intval($_GET['delete']); $conn->query("DELETE FROM Prj_SP2026_products WHERE product_id=$id"); header('Location: products.php'); exit; }
if(isset($_GET['edit'])){ $id=intval($_GET['edit']); $edit=$conn->query("SELECT * FROM Prj_SP2026_products WHERE product_id=$id")->fetch_assoc(); }
if($_SERVER['REQUEST_METHOD']==='POST'){
    $category_id=intval($_POST['category_id']); $name=$_POST['product_name']; $desc=$_POST['product_description']; $price=floatval($_POST['price']); $image=$_POST['image_name']; $status=$_POST['status'];
    if(!empty($_POST['product_id'])){ $id=intval($_POST['product_id']); $stmt=$conn->prepare("UPDATE Prj_SP2026_products SET category_id=?, product_name=?, product_description=?, price=?, image_name=?, status=? WHERE product_id=?"); $stmt->bind_param('issdssi',$category_id,$name,$desc,$price,$image,$status,$id); }
    else { $stmt=$conn->prepare("INSERT INTO Prj_SP2026_products (category_id, product_name, product_description, price, image_name, status) VALUES (?,?,?,?,?,?)"); $stmt->bind_param('issdss',$category_id,$name,$desc,$price,$image,$status); }
    $stmt->execute(); header('Location: products.php'); exit;
}
$categories=$conn->query("SELECT * FROM Prj_SP2026_categories ORDER BY category_name");
$rows=$conn->query("SELECT p.*, c.category_name FROM Prj_SP2026_products p JOIN Prj_SP2026_categories c ON p.category_id=c.category_id ORDER BY p.product_id DESC");
?>
<h1>Manage Products</h1>
<div class="alert alert-info">Image upload is not used. Type the image filename only, then manually FTP that image into <strong>assets/images/</strong>.</div>
<div class="card p-3 mb-4"><form method="post"><input type="hidden" name="product_id" value="<?php echo $edit['product_id'] ?? ''; ?>"><div class="row g-3"><div class="col-md-3"><label>Category</label><select name="category_id" class="form-select" required><?php while($c=$categories->fetch_assoc()): ?><option value="<?php echo $c['category_id']; ?>" <?php echo (($edit['category_id'] ?? '')==$c['category_id'])?'selected':''; ?>><?php echo htmlspecialchars($c['category_name']); ?></option><?php endwhile; ?></select></div><div class="col-md-3"><label>Product Name</label><input name="product_name" class="form-control" required value="<?php echo htmlspecialchars($edit['product_name'] ?? ''); ?>"></div><div class="col-md-2"><label>Price</label><input type="number" step="0.01" name="price" class="form-control" required value="<?php echo htmlspecialchars($edit['price'] ?? ''); ?>"></div><div class="col-md-2"><label>Image Filename</label><input name="image_name" class="form-control" placeholder="example.jpg" value="<?php echo htmlspecialchars($edit['image_name'] ?? 'placeholder.jpg'); ?>"></div><div class="col-md-2"><label>Status</label><select name="status" class="form-select"><option>Active</option><option <?php echo (($edit['status'] ?? '')==='Inactive')?'selected':''; ?>>Inactive</option></select></div><div class="col-md-12"><label>Description</label><textarea name="product_description" class="form-control" rows="3" required><?php echo htmlspecialchars($edit['product_description'] ?? ''); ?></textarea></div><div class="col-md-2"><button class="btn btn-primary">Save Product</button></div></div></form></div>
<table class="table table-bordered table-striped"><tr><th>ID</th><th>Image</th><th>Name</th><th>Category</th><th>Price</th><th>Status</th><th>Action</th></tr><?php while($r=$rows->fetch_assoc()): ?><tr><td><?php echo $r['product_id']; ?></td><td><img src="../assets/images/<?php echo htmlspecialchars($r['image_name']); ?>" width="70"></td><td><?php echo htmlspecialchars($r['product_name']); ?></td><td><?php echo htmlspecialchars($r['category_name']); ?></td><td>$<?php echo number_format($r['price'],2); ?></td><td><?php echo $r['status']; ?></td><td><a class="btn btn-sm btn-warning" href="?edit=<?php echo $r['product_id']; ?>">Edit</a> <a onclick="return confirmDelete()" class="btn btn-sm btn-danger" href="?delete=<?php echo $r['product_id']; ?>">Delete</a></td></tr><?php endwhile; ?></table>
<?php include 'footer.php'; ?>
